name: 'scandir'

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions: {}

jobs:
  scandir:
    name: scandir
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

    - name: Run ShellCheck
      uses: ./
      id: one
      with:
        scandir: testfiles/scandir

    - name: Verify check
      env:
        ONE_FILES: ${{ steps.one.outputs.files }}
      run: |
        expect="testfiles/scandir/run[[:space:]]me.bash"
        notexpect="testfiles/test.bash"

        if [[ ! "$ONE_FILES" =~ $expect ]];then
          echo "::error:: Expected file $expect not found in $ONE_FILES"
          exit 1
        elif [[ "$ONE_FILES" =~ $notexpect ]];then
          echo "::error:: Expected file $notexpect found in $ONE_FILES"
          exit 1
        fi

    - name: Run ShellCheck
      uses: ./
      id: two
      with:
        scandir: './testfiles/scandir'
        ignore_paths: ignore

    - name: Verify check
      env:
        TWO_FILES: ${{ steps.two.outputs.files }}
      run: |
        expect="testfiles/scandir/test.bash"
        notexpect="testfiles/test.bash"

        if [[ ! "$TWO_FILES" =~ $expect ]];then
          echo "::error:: Expected file $expect not found in $TWO_FILES"
          exit 1
        elif [[ "$TWO_FILES" =~ $notexpect ]];then
          echo "::error:: Expected file $notexpect found in $TWO_FILES"
          exit 1
        fi
